# Stage 03: Albert & DeBerta Grid Search (Part 2)

## Imports Load & Clean Dataset

In [1]:
import os
import sys

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if project_root not in sys.path:
    sys.path.append(project_root)
from pathlib import Path

import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from datasets import Dataset
from sklearn.model_selection import train_test_split
import optuna
from optuna.pruners import MedianPruner

from src.training.metrics import compute_metrics, compute_metrics_from_logits
from src.training.tokenization_utils import make_tokenized_datasets, clean_and_prune_by_tokens
from src.training.loss import WeightedBCETrainer
from src.training.search_utils import (
    best_so_far_df, 
    progress_df, 
    reset_study_completely, 
    clean_trial_folders, 
    mark_stale_running_trials_as_fail, 
    remaining_trials_to_run, 
    done_counts,
    OptunaMedianPruningCallback,
    pretty_print_dict,
)

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    EarlyStoppingCallback,
    set_seed,
)

SEED = 42
set_seed(SEED)

ROOT = Path('.').resolve().parents[0]  # run from project root
TRAIN_PATH = ROOT / "data" / "processed" / "pcl_task1_train.csv"
DEV_PATH   = ROOT / "data" / "processed" / "pcl_task1_dev.csv"

OUTPUT_DIR = ROOT / "runs" / "optuna_task1"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

STUDY_DB = str(OUTPUT_DIR / "optuna_pcl_task1.db")  # sqlite db file
STUDY_NAME = "pcl_task1_binary"

train_df = pd.read_csv(TRAIN_PATH)
dev_df   = pd.read_csv(DEV_PATH)

# Keep only what we need
keep_cols = ["par_id", "text", "label_bin"]
train_df = train_df[keep_cols].copy()
dev_df   = dev_df[keep_cols].copy()

train_df["label_bin"] = train_df["label_bin"].astype(int)
dev_df["label_bin"]   = dev_df["label_bin"].astype(int)

print(train_df.shape, dev_df.shape)
print(train_df["label_bin"].value_counts())

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

(8375, 3) (2094, 3)
label_bin
0    7581
1     794
Name: count, dtype: int64

In [2]:
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("CUDA device count:", torch.cuda.device_count())
    print("Current device:", torch.cuda.current_device())
    print("Device name:", torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("No CUDA GPU detected. Using CPU or MPS.")

CUDA available: True
CUDA device count: 1
Current device: 0
Device name: NVIDIA GeForce RTX 4060 Laptop GPU

In [3]:
EXAMPLE_MODEL_NAME = "microsoft/deberta-v3-base"  # one of the two models used for tokenising
CONTEXT_WINDOW = 128  # max tokens to keep (after tokenization)
train_df = clean_and_prune_by_tokens(train_df, EXAMPLE_MODEL_NAME, max_pos_tokens=CONTEXT_WINDOW*1.25)

## Validation split

In [4]:
train_split, val_split = train_test_split(
    train_df,
    test_size=0.15,
    random_state=SEED,
    stratify=train_df["label_bin"], # Keep balance of classes
)

print("train:", train_split["label_bin"].value_counts().to_dict())
print("val  :", val_split["label_bin"].value_counts().to_dict())

ds_train_raw = Dataset.from_pandas(train_split.reset_index(drop=True))
ds_val_raw   = Dataset.from_pandas(val_split.reset_index(drop=True))
ds_dev_raw   = Dataset.from_pandas(dev_df.reset_index(drop=True))

train: {0: 6444, 1: 671}
val  : {0: 1137, 1: 119}

## Define search space for configurations

In [5]:
# Fixed parameters
fixed_maxlen = CONTEXT_WINDOW  # 75% fit under 67 tokens    # trial.suggest_categorical("max_length", [96, 128, 192, 256])
fixed_batch_size = 16
fixed_epochs = 12

In [6]:
from optuna import trial


def objective(trial: optuna.Trial):
    try:
        model_name = trial.suggest_categorical(
            "model_name",
            [
                "microsoft/deberta-v3-base",
                "albert-large-v2",
            ],
        )

        is_deberta = "deberta" in model_name.lower()
        use_fp16 = torch.cuda.is_available() and (not is_deberta)  # DeBERTa can be unstable in fp16, so we disable it for that model
        use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported() and is_deberta

        trial.set_user_attr("fp16", bool(use_fp16))
        trial.set_user_attr("bf16", bool(use_bf16)) # Faster than normal float32 and no mixed precision instability like fp16 (since same range)

        lr          = trial.suggest_float("lr", 5e-6, 5e-5, log=True)
        batch_size  = fixed_batch_size
        weight_decay= trial.suggest_float("weight_decay", 0.0, 0.1)
        warmup_ratio= trial.suggest_float("warmup_ratio", 0.0, 0.15)
        max_length  = fixed_maxlen   
        epochs      = fixed_epochs
        grad_accum  = trial.suggest_categorical("grad_accum", [1, 2])
        pos_weight_scale = 1.5 # up to 1.5x the base pos weight

        tok, ds_train, ds_val, _ = make_tokenized_datasets(model_name, max_length, ds_train_raw, ds_val_raw, ds_dev_raw)

        y = np.array(train_split["label_bin"].values, dtype=int)
        n_pos = (y == 1).sum()
        n_neg = (y == 0).sum()
        base_pos_weight = (n_neg / max(n_pos, 1))
        pos_weight   = trial.suggest_float("pos_weight", 1, base_pos_weight * pos_weight_scale)
        pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float)
        cfg = AutoConfig.from_pretrained(model_name)
        cfg.num_labels = 1  # single logit
        model = AutoModelForSequenceClassification.from_pretrained(model_name, config=cfg)

        trial_dir = OUTPUT_DIR / f"trial_{trial.number:04d}"
        trial_dir.mkdir(parents=True, exist_ok=True)

        args = TrainingArguments(
            output_dir=str(trial_dir),
            seed=SEED,
            data_seed=SEED,
            learning_rate=lr,
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            gradient_accumulation_steps=grad_accum,
            num_train_epochs=epochs,
            weight_decay=weight_decay,
            warmup_ratio=warmup_ratio,
            eval_strategy="epoch",
            save_strategy="epoch",
            logging_strategy="epoch",
            load_best_model_at_end=True,
            metric_for_best_model="f1",
            greater_is_better=True,
            save_total_limit=1,
            fp16=use_fp16,
            bf16=use_bf16,
            report_to="none",
        )

        trainer = WeightedBCETrainer(
            model=model,
            args=args,
            train_dataset=ds_train,
            eval_dataset=ds_val,
            compute_metrics=compute_metrics,
            callbacks=[
                OptunaMedianPruningCallback(trial, monitor="eval_f1"),
                EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.003),
            ],
            pos_weight=pos_weight_tensor,
        )

        cfg_to_print = {
            "model_name": model_name,
            "lr": lr,
            "weight_decay": weight_decay,
            "warmup_ratio": warmup_ratio,
            "max_length": max_length,
            "epochs": epochs,
            "grad_accum": grad_accum,
            "pos_weight": pos_weight,
            "pos_weight_rel": pos_weight / base_pos_weight,
            "fp16": use_fp16,
            "bf16": use_bf16,
        }
        pretty_print_dict(f"Trial {trial.number} config", cfg_to_print)

        trainer.train()
        metrics = trainer.evaluate(ds_val)
        pretty_print_dict(f"Trial {trial.number} metrics", metrics, sort_keys=False)
        return metrics["eval_f1"]

    except torch.cuda.OutOfMemoryError:
        print("OOM: pruning this trial")
        torch.cuda.empty_cache()
        raise optuna.TrialPruned()
    except KeyboardInterrupt:
        try:
            trial.set_user_attr("interrupted", True)
        except Exception:
            pass
        raise  # stops the optimize call
    except RuntimeError as e:
        if "out of memory" in str(e).lower():
            print("OOM (RuntimeError): pruning this trial")
            torch.cuda.empty_cache()
            raise optuna.TrialPruned()
        else:
            raise
    finally:
        try:
            del model
            torch.cuda.empty_cache()
        except Exception:
            pass

In [7]:
storage_url = f"sqlite:///{STUDY_DB}"

study = optuna.create_study(
    study_name=STUDY_NAME,
    direction="maximize",
    storage=storage_url,
    load_if_exists=True,
    pruner=MedianPruner(n_startup_trials=13, n_warmup_steps=4, n_min_trials=7, interval_steps=1)
)

stale = mark_stale_running_trials_as_fail(study)
if stale:
    print("Marked stale RUNNING trials as FAIL:", stale)

TARGET_DONE = 50  # total COMPLETE+PRUNED (across sessions)
to_run = remaining_trials_to_run(study, TARGET_DONE)

[I 2026-02-21 02:25:52,689] A new study created in RDB with name: pcl_task1_binary

In [8]:
print("Trial state counts:", done_counts(study))
print(f"Will run {to_run} new trials to reach {TARGET_DONE} done (COMPLETE+PRUNED).")

try:
    if to_run > 0:
        study.optimize(objective, n_trials=to_run, gc_after_trial=True)
except KeyboardInterrupt:
    print("Interrupted. Rerun this cell to continue toward the target.")

print("Trial state counts:", done_counts(study))
print("Best f1:", study.best_value)
print("Best params:", study.best_params)

Trial state counts: {'RUNNING': 0, 'COMPLETE': 0, 'PRUNED': 0, 'FAIL': 0, 'WAITING': 0}
Will run 50 new trials to reach 50 done (COMPLETE+PRUNED).

Map: 100%|██████████| 7115/7115 [00:00<00:00, 16341.58 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 17888.77 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 18164.33 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 520.89it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.50s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 02:32:15,668] Trial 0 finished with value: 0.1730909090909091 and parameters: {'model_name': 'microsoft/deberta-v3-base', 'lr': 1.0651076555338613e-05, 'weight_decay': 0.06923412373106422, 'warmup_ratio': 0.1045650344860999, 'grad_accum': 1, 'pos_weight': 12.80594397714353}. Best is trial 0 with value: 0.1730909090909091.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14372.63 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14019.93 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15794.20 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 356.87it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.53it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.77it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.84it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.01it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 02:46:17,438] Trial 1 finished with value: 0.1730909090909091 and parameters: {'model_name': 'albert-large-v2', 'lr': 2.723515446109626e-05, 'weight_decay': 0.03336407339026065, 'warmup_ratio': 0.004137850829345352, 'grad_accum': 2, 'pos_weight': 8.128231177924704}. Best is trial 0 with value: 0.1730909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13496.82 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14141.08 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14274.94 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 439.91it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.53s/it]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.13s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.30s/it]
There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 02:52:41,365] Trial 2 finished with value: 0.0 and parameters: {'model_name': 'microsoft/deberta-v3-base', 'lr': 4.485636614664399e-05, 'weight_decay': 0.09021296940283607, 'warmup_ratio': 0.044889816089396385, 'grad_accum': 1, 'pos_weight': 11.351816004296362}. Best is trial 0 with value: 0.1730909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13218.23 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13135.96 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 13498.72 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 452.61it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]
Writing model shards: 100%|██████████| 1/1 [00:03<00:00,  3.97s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 02:59:23,098] Trial 3 finished with value: 0.0 and parameters: {'model_name': 'microsoft/deberta-v3-base', 'lr': 5.563087514459143e-06, 'weight_decay': 0.03434626081165437, 'warmup_ratio': 0.1417388668046247, 'grad_accum': 1, 'pos_weight': 8.708980412652986}. Best is trial 0 with value: 0.1730909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13459.13 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13994.76 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 13848.07 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 383.61it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.43s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.48s/it]
There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 03:05:20,246] Trial 4 finished with value: 0.1730909090909091 and parameters: {'model_name': 'microsoft/deberta-v3-base', 'lr': 1.0961832390998731e-05, 'weight_decay': 0.07246480023064658, 'warmup_ratio': 0.12476903035201685, 'grad_accum': 2, 'pos_weight': 11.708202447443151}. Best is trial 0 with value: 0.1730909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 12460.76 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13488.55 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14410.01 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 341.54it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.16it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.24it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.91it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.10it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  optuna_warn(

[I 2026-02-21 03:22:37,132] Trial 5 finished with value: 0.17321688500727803 and parameters: {'model_name': 'albert-large-v2', 'lr': 1.9818362407307498e-05, 'weight_decay': 0.08244411188551931, 'warmup_ratio': 0.026749890536192717, 'grad_accum': 2, 'pos_weight': 14.074138763083205}. Best is trial 5 with value: 0.17321688500727803.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13614.35 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14175.55 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 13652.78 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 437.60it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.53s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
Writing model shards: 100%|██████████| 1/1 [00:04<00:00,  4.42s/it]
There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 03:28:27,563] Trial 6 finished with value: 0.0 and parameters: {'model_name': 'microsoft/deberta-v3-base', 'lr': 2.1934465832834804e-05, 'weight_decay': 0.0960286183971632, 'warmup_ratio': 0.008149263341900415, 'grad_accum': 2, 'pos_weight': 11.42394888824102}. Best is trial 5 with value: 0.17321688500727803.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13214.59 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13901.76 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15214.60 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 277.47it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.32it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.14it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  optuna_warn(

[I 2026-02-21 03:46:20,807] Trial 7 finished with value: 0.5283018867924528 and parameters: {'model_name': 'albert-large-v2', 'lr': 1.0026794632051424e-05, 'weight_decay': 0.08171119849749564, 'warmup_ratio': 0.08874610540738027, 'grad_accum': 1, 'pos_weight': 3.6800042056114295}. Best is trial 7 with value: 0.5283018867924528.
Map: 100%|██████████| 7115/7115 [-00:01<00:00, -4145.02 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 12794.44 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14054.91 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 329.84it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.11it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  optuna_warn(

[I 2026-02-21 04:07:11,282] Trial 8 finished with value: 0.5504587155963303 and parameters: {'model_name': 'albert-large-v2', 'lr': 1.2346147133777894e-05, 'weight_decay': 0.07443102217916546, 'warmup_ratio': 0.14945872041910818, 'grad_accum': 2, 'pos_weight': 5.971158784046863}. Best is trial 8 with value: 0.5504587155963303.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 12180.94 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13981.42 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14158.68 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 393.92it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.64it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 04:31:48,314] Trial 9 finished with value: 0.5469387755102041 and parameters: {'model_name': 'albert-large-v2', 'lr': 1.3737489908652345e-05, 'weight_decay': 0.09112285395540452, 'warmup_ratio': 0.03630340886073179, 'grad_accum': 2, 'pos_weight': 1.600264377704728}. Best is trial 8 with value: 0.5504587155963303.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13787.57 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14506.13 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14572.16 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 366.49it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  optuna_warn(

[I 2026-02-21 04:52:22,502] Trial 10 finished with value: 0.5811965811965812 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.521412355592228e-06, 'weight_decay': 0.0056544682967779245, 'warmup_ratio': 0.06449985184873279, 'grad_accum': 2, 'pos_weight': 5.829660017544584}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14915.81 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14388.42 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14589.78 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 385.32it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 05:16:35,025] Trial 11 finished with value: 0.5692883895131086 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.188532046269828e-06, 'weight_decay': 0.006082296254732195, 'warmup_ratio': 0.06528361703043796, 'grad_accum': 2, 'pos_weight': 5.456747670629779}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14762.20 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14931.38 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14532.90 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 401.82it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  optuna_warn(

[I 2026-02-21 05:47:36,223] Trial 12 finished with value: 0.5606694560669456 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.2302862423233264e-06, 'weight_decay': 0.0007191886652707464, 'warmup_ratio': 0.06434582097012101, 'grad_accum': 2, 'pos_weight': 5.727581042039599}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 16052.41 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15048.76 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16476.92 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 396.94it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 4 is already reported.
  optuna_warn(

[I 2026-02-21 06:01:28,510] Trial 13 finished with value: 0.41140529531568226 and parameters: {'model_name': 'albert-large-v2', 'lr': 7.1439598360524425e-06, 'weight_decay': 0.0007734005395472893, 'warmup_ratio': 0.0635241050612538, 'grad_accum': 2, 'pos_weight': 5.4161019134252895}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 16450.15 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16134.75 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16341.50 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 453.08it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 9 is already reported.
  optuna_warn(

[I 2026-02-21 06:32:30,779] Trial 14 finished with value: 0.5581395348837209 and parameters: {'model_name': 'albert-large-v2', 'lr': 7.073146677325845e-06, 'weight_decay': 0.013040167920752155, 'warmup_ratio': 0.08602385926227228, 'grad_accum': 2, 'pos_weight': 3.0187527722169585}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14083.97 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15559.51 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15911.40 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 389.23it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.13it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  optuna_warn(

[I 2026-02-21 06:59:50,561] Trial 15 finished with value: 0.5485232067510548 and parameters: {'model_name': 'albert-large-v2', 'lr': 7.878516029704225e-06, 'weight_decay': 0.022433129025070893, 'warmup_ratio': 0.055448548173892456, 'grad_accum': 2, 'pos_weight': 9.347098839899958}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15081.22 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16796.26 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 13935.18 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 396.30it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 07:24:06,585] Trial 16 finished with value: 0.5555555555555556 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.010262175845761e-06, 'weight_decay': 0.05288654010993779, 'warmup_ratio': 0.10363923366326211, 'grad_accum': 2, 'pos_weight': 6.815146247653272}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15990.91 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14994.96 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15523.94 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 425.90it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 07:48:13,893] Trial 17 finished with value: 0.5496688741721855 and parameters: {'model_name': 'albert-large-v2', 'lr': 8.10275637064777e-06, 'weight_decay': 0.016091036102244008, 'warmup_ratio': 0.08019327965220834, 'grad_accum': 2, 'pos_weight': 4.390252578024199}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14885.56 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15717.06 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15067.21 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 358.39it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
Writing model shards: 100%|██████████| 1/1 [-00:01<00:00, -0.61it/s]
[I 2026-02-21 08:01:48,366] Trial 18 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15770.89 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15213.17 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14626.96 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 339.29it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.26it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.79it/s]
[I 2026-02-21 08:15:21,382] Trial 19 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15206.28 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16346.89 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15602.26 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 365.38it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
Writing model shards: 100%|██████████| 1/1 [-00:02<00:00, -0.42it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 08:39:09,133] Trial 20 finished with value: 0.5423728813559322 and parameters: {'model_name': 'albert-large-v2', 'lr': 6.483294956931441e-06, 'weight_decay': 0.04463678459581487, 'warmup_ratio': 0.05114705584581801, 'grad_accum': 2, 'pos_weight': 1.0728305108375729}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14844.86 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14984.60 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16095.19 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 345.25it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 09:03:24,715] Trial 21 finished with value: 0.5454545454545454 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.838532738718396e-06, 'weight_decay': 0.0021089854406719753, 'warmup_ratio': 0.06631831104324394, 'grad_accum': 2, 'pos_weight': 5.287150623790868}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 12739.26 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14108.51 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14576.46 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 389.57it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]
[I 2026-02-21 09:17:06,430] Trial 22 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14791.58 examples/s]
Map: 100%|██████████| 1256/1256 [-00:02<00:00, -440.40 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15718.84 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 376.86it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 09:41:28,258] Trial 23 finished with value: 0.5480427046263345 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.369561698074258e-06, 'weight_decay': 0.006227482773062525, 'warmup_ratio': 0.07474782860228768, 'grad_accum': 2, 'pos_weight': 6.517223917548536}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13371.00 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14021.95 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14892.69 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 421.39it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 10:05:37,402] Trial 24 finished with value: 0.5492957746478874 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.0161545267033244e-06, 'weight_decay': 0.019775650875174598, 'warmup_ratio': 0.04433833617661148, 'grad_accum': 2, 'pos_weight': 9.640942351885313}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 16178.59 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16416.32 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14902.42 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 416.06it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.85it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 10 is already reported.
  optuna_warn(

[I 2026-02-21 10:39:55,241] Trial 25 finished with value: 0.56 and parameters: {'model_name': 'albert-large-v2', 'lr': 8.629853771749342e-06, 'weight_decay': 0.024052814291450095, 'warmup_ratio': 0.059754711984246485, 'grad_accum': 2, 'pos_weight': 4.6522290555877195}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14093.09 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14229.89 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 10414.34 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 413.64it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.60s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.33s/it]
Writing model shards: 100%|██████████| 1/1 [00:03<00:00,  3.04s/it]
[I 2026-02-21 10:46:23,048] Trial 26 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15680.81 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16085.54 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16372.61 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 517.98it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.61it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  optuna_warn(

[I 2026-02-21 11:03:41,421] Trial 27 finished with value: 0.5381818181818182 and parameters: {'model_name': 'albert-large-v2', 'lr': 6.2748934633366e-06, 'weight_decay': 0.0033391832186164677, 'warmup_ratio': 0.11587225532256654, 'grad_accum': 2, 'pos_weight': 6.087911160314666}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15822.54 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14391.92 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16174.18 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 501.52it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
[I 2026-02-21 11:17:24,267] Trial 28 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.525096525096525
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14530.30 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 12920.02 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 13954.65 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 474.13it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.98s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
[I 2026-02-21 11:23:43,211] Trial 29 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15650.26 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14535.07 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15572.47 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 433.44it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.54it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
[I 2026-02-21 11:37:22,657] Trial 30 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.5230769230769231
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15553.48 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16102.40 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15257.82 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 427.65it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.19it/s]
[I 2026-02-21 11:51:06,165] Trial 31 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14977.83 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15312.35 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16301.86 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 401.25it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.31it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.42it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.27it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.85it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.29it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.19it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 8 is already reported.
  optuna_warn(

[I 2026-02-21 12:18:38,702] Trial 32 finished with value: 0.5761316872427984 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.859367466902579e-06, 'weight_decay': 0.0001322089043732977, 'warmup_ratio': 0.06990038526135625, 'grad_accum': 2, 'pos_weight': 5.747020684927196}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15287.24 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14895.46 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15678.44 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 404.88it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.91it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.27it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.10it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.10it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  optuna_warn(

[I 2026-02-21 12:39:28,788] Trial 33 finished with value: 0.562962962962963 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.986173551250387e-06, 'weight_decay': 0.0001717804777140626, 'warmup_ratio': 0.06910164588671282, 'grad_accum': 2, 'pos_weight': 8.101215117003479}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14901.62 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14859.15 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15255.30 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 513.15it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.63it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.94it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.04it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.15it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.05it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.92it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 13:03:27,289] Trial 34 finished with value: 0.5555555555555556 and parameters: {'model_name': 'albert-large-v2', 'lr': 6.222405314049172e-06, 'weight_decay': 0.009184423971090747, 'warmup_ratio': 0.09716336297327677, 'grad_accum': 2, 'pos_weight': 8.389529851842914}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13947.92 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13505.18 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 13737.71 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 384.30it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
Writing model shards: 100%|██████████| 1/1 [00:04<00:00,  4.21s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]
[I 2026-02-21 13:09:56,684] Trial 35 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14645.81 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15069.69 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15442.63 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 406.52it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  optuna_warn(

[I 2026-02-21 13:31:42,925] Trial 36 finished with value: 0.5537190082644629 and parameters: {'model_name': 'albert-large-v2', 'lr': 7.07021225276763e-06, 'weight_decay': 0.006481558181151881, 'warmup_ratio': 0.08146047100813339, 'grad_accum': 2, 'pos_weight': 10.644931127778799}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 13563.89 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13420.58 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 12799.46 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 368.70it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]
Writing model shards: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
[I 2026-02-21 13:37:24,230] Trial 37 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [-00:02<00:00, -2905.07 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15602.64 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15538.28 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 392.41it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.84it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.68it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.26it/s]
[I 2026-02-21 13:51:17,079] Trial 38 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.49444444444444446
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14154.31 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13822.76 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 11950.87 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 413.84it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.81it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
[I 2026-02-21 14:05:08,810] Trial 39 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.5328467153284672
Map: 100%|██████████| 7115/7115 [00:00<00:00, 12974.79 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 13962.23 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 12529.54 examples/s]
Loading weights: 100%|██████████| 198/198 [00:00<00:00, 434.12it/s, Materializing param=deberta.encoder.rel_embeddings.weight]
DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.39s/it]
Writing model shards: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]
[I 2026-02-21 14:10:45,467] Trial 40 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.0
Map: 100%|██████████| 7115/7115 [00:01<00:00, 6475.24 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14620.67 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 14845.29 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 408.01it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.74it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 14:34:38,821] Trial 41 finished with value: 0.5477707006369427 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.050475352303849e-06, 'weight_decay': 0.0005294699018145686, 'warmup_ratio': 0.05475588726330311, 'grad_accum': 2, 'pos_weight': 5.721083187438452}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14839.95 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14773.94 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 11534.59 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 370.54it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.49it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.52it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 14:59:24,082] Trial 42 finished with value: 0.539568345323741 and parameters: {'model_name': 'albert-large-v2', 'lr': 5.577138516084537e-06, 'weight_decay': 0.001467060275996251, 'warmup_ratio': 0.0685107984943175, 'grad_accum': 2, 'pos_weight': 7.474115369343259}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14091.53 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16508.61 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15792.76 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 425.08it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.73it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.60it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.99it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.36it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 15:23:38,442] Trial 43 finished with value: 0.5666666666666667 and parameters: {'model_name': 'albert-large-v2', 'lr': 6.662307667644682e-06, 'weight_decay': 0.007896439066929325, 'warmup_ratio': 0.06152541931361349, 'grad_accum': 2, 'pos_weight': 5.661884638639895}. Best is trial 10 with value: 0.5811965811965812.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15261.66 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15051.13 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16299.83 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 446.89it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.10it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.01s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.71it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.93it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 15:48:01,822] Trial 44 finished with value: 0.5890909090909091 and parameters: {'model_name': 'albert-large-v2', 'lr': 6.7039199103625656e-06, 'weight_decay': 0.009102494923995078, 'warmup_ratio': 0.07443779268203606, 'grad_accum': 2, 'pos_weight': 3.9603861290668045}. Best is trial 44 with value: 0.5890909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 15753.58 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 16361.46 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15223.75 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 464.91it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.46it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.34it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.33it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 6 is already reported.
  optuna_warn(

[I 2026-02-21 16:09:20,150] Trial 45 finished with value: 0.5676855895196506 and parameters: {'model_name': 'albert-large-v2', 'lr': 6.946152563373682e-06, 'weight_decay': 0.01816801998930426, 'warmup_ratio': 0.08966039872129508, 'grad_accum': 2, 'pos_weight': 3.5090988176715308}. Best is trial 44 with value: 0.5890909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14930.05 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15370.97 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 16206.51 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 439.82it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.35it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.26it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.33it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.19it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 16:33:29,552] Trial 46 finished with value: 0.5627376425855514 and parameters: {'model_name': 'albert-large-v2', 'lr': 7.548994369280001e-06, 'weight_decay': 0.02074325752524414, 'warmup_ratio': 0.0920034872676537, 'grad_accum': 2, 'pos_weight': 3.90157806615761}. Best is trial 44 with value: 0.5890909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14584.65 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 14874.13 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15224.62 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 391.33it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.05it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.43it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.01it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.22it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 5 is already reported.
  optuna_warn(

[I 2026-02-21 16:50:56,059] Trial 47 finished with value: 0.563265306122449 and parameters: {'model_name': 'albert-large-v2', 'lr': 8.885303376191273e-06, 'weight_decay': 0.01589073945554236, 'warmup_ratio': 0.10895472301270226, 'grad_accum': 2, 'pos_weight': 3.2476428197262885}. Best is trial 44 with value: 0.5890909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14463.90 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15876.26 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 15370.58 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 395.46it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.74it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.46it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

/home/joshua_killa/.pyenv/versions/pcl-env/lib/python3.10/site-packages/optuna/trial/_trial.py:503: UserWarning: The reported value is ignored because this `step` 7 is already reported.
  optuna_warn(

[I 2026-02-21 17:15:23,744] Trial 48 finished with value: 0.570281124497992 and parameters: {'model_name': 'albert-large-v2', 'lr': 7.93823918181687e-06, 'weight_decay': 0.03784422209979671, 'warmup_ratio': 0.12756958839250926, 'grad_accum': 2, 'pos_weight': 2.36848672654542}. Best is trial 44 with value: 0.5890909090909091.
Map: 100%|██████████| 7115/7115 [00:00<00:00, 14646.40 examples/s]
Map: 100%|██████████| 1256/1256 [00:00<00:00, 15180.16 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 12453.75 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 389.06it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.24it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.47it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.49it/s]
[I 2026-02-21 17:29:20,612] Trial 49 pruned. MedianPruner: pruned at epoch=4 with eval_f1=0.5229357798165137

Trial state counts: {'RUNNING': 0, 'COMPLETE': 36, 'PRUNED': 14, 'FAIL': 0, 'WAITING': 0}
Best f1: 0.5890909090909091
Best params: {'model_name': 'albert-large-v2', 'lr': 6.7039199103625656e-06, 'weight_decay': 0.009102494923995078, 'warmup_ratio': 0.07443779268203606, 'grad_accum': 2, 'pos_weight': 3.9603861290668045}

### Grid search database operations

In [9]:
best_so_far_df(study, 10)

,number,state,value,params_grad_accum,params_lr,params_model_name,params_pos_weight,params_warmup_ratio,params_weight_decay,user_attrs_bf16,user_attrs_fp16
44,44,COMPLETE,0.589091,2,0.000007,albert-large-v2,3.960386,0.074438,0.009102,False,True
10,10,COMPLETE,0.581197,2,0.000006,albert-large-v2,5.829660,0.064500,0.005654,False,True
32,32,COMPLETE,0.576132,2,0.000006,albert-large-v2,5.747021,0.069900,0.000132,False,True
48,48,COMPLETE,0.570281,2,0.000008,albert-large-v2,2.368487,0.127570,0.037844,False,True
11,11,COMPLETE,0.569288,2,0.000005,albert-large-v2,5.456748,0.065284,0.006082,False,True
45,45,COMPLETE,0.567686,2,0.000007,albert-large-v2,3.509099,0.089660,0.018168,False,True
43,43,COMPLETE,0.566667,2,0.000007,albert-large-v2,5.661885,0.061525,0.007896,False,True
47,47,COMPLETE,0.563265,2,0.000009,albert-large-v2,3.247643,0.108955,0.015891,False,True
33,33,COMPLETE,0.562963,2,0.000006,albert-large-v2,8.101215,0.069102,0.000172,False,True
46,46,COMPLETE,0.562738,2,0.000008,albert-large-v2,3.901578,0.092003,0.020743,False,True

## Train best configuration

In [13]:
# second_best = sorted(study.trials, key=lambda t: t.value if t.value is not None else float("-inf"), reverse=True)[1]
best = study.best_params
best_model = best["model_name"]

is_deberta = "deberta" in best_model.lower()
use_fp16 = torch.cuda.is_available() and (not is_deberta)  # DeBERTa can be unstable in fp16, so we disable it for that model
use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported() and is_deberta

# rebuild datasets: train on (train+val), evaluate on dev
full_train = pd.concat([train_split, val_split], ignore_index=True)
ds_full_train_raw = Dataset.from_pandas(full_train.reset_index(drop=True))

tok = AutoTokenizer.from_pretrained(best_model, use_fast=True)

def tok_fn(batch):
    texts = [str(x) if x is not None else "" for x in batch["text"]]
    tokenized = tok(
        texts,
        truncation=True,
        padding="max_length",
        max_length=fixed_maxlen,
    )
    if "label_bin" in batch:
        tokenized["labels"] = [float(x) for x in batch["label_bin"]]
    return dict(tokenized)

# Tokenize datasets & truncate/pad them to max length
ds_full_train = ds_full_train_raw.map(tok_fn, batched=True)
ds_dev = ds_dev_raw.map(tok_fn, batched=True)

# Only rename if needed
if "labels" not in ds_full_train.column_names and "label_bin" in ds_full_train.column_names:
    ds_full_train = ds_full_train.rename_column("label_bin", "labels")
if "labels" not in ds_dev.column_names and "label_bin" in ds_dev.column_names:
    ds_dev = ds_dev.rename_column("label_bin", "labels")

# Remove unnecessary columns
ds_full_train = ds_full_train.remove_columns([c for c in ds_full_train.column_names if c not in ["input_ids", "attention_mask", "labels"]])
ds_dev = ds_dev.remove_columns([c for c in ds_dev.column_names if c not in ["input_ids", "attention_mask", "labels"]])

pos_weight_tensor = torch.tensor(best["pos_weight"], dtype=torch.float)

cfg = AutoConfig.from_pretrained(best_model)
cfg.num_labels = 1
model = AutoModelForSequenceClassification.from_pretrained(best_model, config=cfg)

final_dir = OUTPUT_DIR / "best_final_model"
final_dir.mkdir(parents=True, exist_ok=True)

args = TrainingArguments(
    output_dir=str(final_dir),
    seed=SEED,
    data_seed=SEED,
    learning_rate=best["lr"],
    per_device_train_batch_size=fixed_batch_size,
    per_device_eval_batch_size=fixed_batch_size,
    gradient_accumulation_steps=best["grad_accum"],
    num_train_epochs=15,
    weight_decay=best["weight_decay"],
    warmup_ratio=best["warmup_ratio"],
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    save_total_limit=1,
    fp16=use_fp16,
    bf16=use_bf16,
    report_to="none",
)

trainer = WeightedBCETrainer(
    model=model,
    args=args,
    train_dataset=ds_full_train,
    eval_dataset=ds_dev,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=10)],
    pos_weight=pos_weight_tensor,
)

trainer.train()
dev_metrics = trainer.evaluate(ds_dev)
dev_metrics

Map: 100%|██████████| 8371/8371 [00:01<00:00, 7998.74 examples/s]
Map: 100%|██████████| 2094/2094 [00:00<00:00, 7289.01 examples/s]
Loading weights: 100%|██████████| 25/25 [00:00<00:00, 144.20it/s, Materializing param=albert.pooler.weight]
AlbertForSequenceClassification LOAD REPORT from: albert-large-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.bias             | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.dense.bias       | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards: 100%|██████████| 1/1 [-00:00<00:00, -11.59it/s]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.10it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.96it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.31it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.17it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.05it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
There were missing keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.weight', 'albert.embeddings.LayerNorm.bias', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['albert.embeddings.LayerNorm.beta', 'albert.embeddings.LayerNorm.gamma', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.beta', 'albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.gamma'].

{'eval_loss': 1.135825753211975,
 'eval_f1': 0.5714285714285714,
 'eval_precision': 0.5078125,
 'eval_recall': 0.6532663316582915,
 'eval_accuracy': 0.9068767908309455,
 'eval_acc_nonpcl': 0.9335092348284956,
 'eval_acc_pcl': 0.6532663316582882,
 'eval_tp': 130,
 'eval_tn': 1769,
 'eval_fp': 126,
 'eval_fn': 69,
 'eval_runtime': 21.4345,
 'eval_samples_per_second': 97.693,
 'eval_steps_per_second': 6.112,
 'epoch': 15.0}